export const commune = [
  { id: 1, name: 'Calle Larga' },
  { id: 2, name: 'Los Andes' },
  { id: 3, name: 'Rinconada' },
  { id: 4, name: 'San Esteban' },
  { id: 5, name: 'Cabildo' },
  { id: 6, name: 'La Ligua' },
  { id: 7, name: 'Papudo' },
  { id: 8, name: 'Petorca' },
  { id: 9, name: 'Zapallar' },
  { id: 10, name: 'Hijuelas' },
  { id: 11, name: 'La Calera' },
  { id: 12, name: 'La Cruz' },
  { id: 13, name: 'Nogales' },
  { id: 14, name: 'Quillota' },
  { id: 15, name: 'Algarrobo' },
  { id: 16, name: 'Cartagena' },
  { id: 17, name: 'El Quisco' },
  { id: 18, name: 'El Tabo' },
  { id: 19, name: 'San Antonio' },
  { id: 20, name: 'Santo Domingo' },
  { id: 21, name: 'Catemu' },
  { id: 22, name: 'Llay-Llay' },
  { id: 23, name: 'Panquehue' },
  { id: 24, name: 'Putaendo' },
  { id: 25, name: 'San Felipe' },
  { id: 26, name: 'Santa María' },
  { id: 27, name: 'Casablanca' },
  { id: 28, name: 'Concón' },
  { id: 29, name: 'Juan Fernández' },
  { id: 30, name: 'Puchuncaví' },
  { id: 31, name: 'Quintero' },
  { id: 32, name: 'Valparaíso' },
  { id: 33, name: 'Viña del Mar' },
  { id: 34, name: 'Limache' },
  { id: 35, name: 'Olmué' },
  { id: 36, name: 'Quilpué' },
  { id: 37, name: 'Villa Alemana' },
];
